export const ROLL_DICE_START = 'ROLL_DICE_START';
export const EVALUATE_DICE_RESULT = 'EVALUATE_DICE_RESULT';
export const ROLL_DICE_END = 'ROLL_DICE_END';
export const PLAYER_TURN = 'PLAYER_TURN';
export const NEW_GAME = 'NEW_GAME';
